name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Package application
        run: mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-artifact
          path: target/my-app.jar # Adjust this path to your built artifact's location
