name: Build Workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK (Java 11, adjust version if needed)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: maven

    # Step 3: Build with Maven
    - name: Build with Maven
      run: mvn clean package

    # Step 4: Archive the build output
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-application-artifact
        path: target/*.jar  # Adjust path based on your build output directory

    # Optional: Run tests
    - name: Run Tests
      run: mvn test

  # Add a job to download the artifact (optional step)
  download-artifact:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Download the artifact
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: java-application-artifact
        path: ./downloaded-artifact
